/**
 * Command Code model capability table.
 *
 * Transcribed from the official CLI's own model registry (the table it builds
 * `createModelRegistry` over), which is the only authoritative source for which
 * models accept image input and which reasoning levels each one exposes: the
 * public `/provider/v1/models` listing carries an id, a display name, and a
 * context length, but says nothing about modalities or reasoning.
 *
 * Family heuristics are not a substitute. Within one vendor the split is not
 * derivable from the id: `deepseek/deepseek-v4-flash` is text-only while
 * `deepseek/deepseek-v4.1-flash` and `deepseek/deepseek-v4-flash-vision-exp` take
 * images, and `z-ai/glm-5.3-flash` takes images while `zai-org/GLM-5.3` does not.
 */

export interface CommandCodeModelDef {
  id: string
  name: string
  /** Accepted request modalities, exactly as the registry declares them. */
  inputModalities: Array<'text' | 'image'>
  /** Selectable reasoning levels; empty when the model exposes none. */
  reasoningEfforts: string[]
  /** Context window the registry declares, when it declares one. */
  contextWindow: number | null
  /** Output cap the registry declares, when it declares one. */
  maxTokens: number | null
}

/** Every model the Command Code registry describes, in registry order. */
export const COMMAND_CODE_MODELS: readonly CommandCodeModelDef[] = [
  {
    id: 'claude-sonnet-5',
    name: 'Claude Sonnet 5',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'claude-fable-5-1',
    name: 'Claude Fable 5.1',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'claude-fable-5',
    name: 'Claude Fable 5',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'claude-opus-5',
    name: 'Claude Opus 5',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'claude-opus-4-8',
    name: 'Claude Opus 4.8',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'claude-opus-4-7',
    name: 'Claude Opus 4.7',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'claude-haiku-4-5-20251001',
    name: 'Claude Haiku 4.5',
    inputModalities: ['text', 'image'],
    reasoningEfforts: [],
    contextWindow: 200000,
    maxTokens: null,
  },
  {
    id: 'gpt-6-astra',
    name: 'GPT-6 Astra',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    contextWindow: 1050000,
    maxTokens: null,
  },
  {
    id: 'gpt-5.6-sol',
    name: 'GPT-5.6 Sol',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    contextWindow: 1050000,
    maxTokens: null,
  },
  {
    id: 'gpt-5.6-terra',
    name: 'GPT-5.6 Terra',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    contextWindow: 1050000,
    maxTokens: null,
  },
  {
    id: 'gpt-5.6-luna',
    name: 'GPT-5.6 Luna',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    contextWindow: 1050000,
    maxTokens: null,
  },
  {
    id: 'gpt-5.5',
    name: 'GPT-5.5',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh'],
    contextWindow: 400000,
    maxTokens: null,
  },
  {
    id: 'gpt-5.4',
    name: 'GPT-5.4',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh'],
    contextWindow: 400000,
    maxTokens: null,
  },
  {
    id: 'gpt-5.3-codex',
    name: 'GPT-5.3 Codex',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh'],
    contextWindow: 400000,
    maxTokens: null,
  },
  {
    id: 'gpt-5.4-mini',
    name: 'GPT-5.4 Mini',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high'],
    contextWindow: 400000,
    maxTokens: null,
  },
  {
    id: 'deepseek/deepseek-v4-pro',
    name: 'DeepSeek V4 Pro (latest)',
    inputModalities: ['text'],
    reasoningEfforts: ['high', 'max'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'deepseek/deepseek-v4-flash',
    name: 'DeepSeek V4 Flash (latest)',
    inputModalities: ['text'],
    reasoningEfforts: ['high', 'max'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'deepseek/deepseek-v4-flash-vision-exp',
    name: 'DeepSeek V4 Flash Vision (exp)',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['high', 'max'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'deepseek/deepseek-v4-flash-fast',
    name: 'DeepSeek V4 Flash Fast',
    inputModalities: ['text'],
    reasoningEfforts: ['low', 'high', 'max'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'deepseek/deepseek-v4.1-flash',
    name: 'DeepSeek V4.1 Flash',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'high', 'max'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'moonshotai/Kimi-K3',
    name: 'Kimi K3',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'high', 'max'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'moonshotai/Kimi-K2.7-Code',
    name: 'Kimi K2.7 Code',
    inputModalities: ['text', 'image'],
    reasoningEfforts: [],
    contextWindow: 256000,
    maxTokens: null,
  },
  {
    id: 'moonshotai/Kimi-K2.7-Code-Highspeed',
    name: 'Kimi K2.7 Code HighSpeed',
    inputModalities: ['text', 'image'],
    reasoningEfforts: [],
    contextWindow: 262000,
    maxTokens: null,
  },
  {
    id: 'moonshotai/Kimi-K2.6',
    name: 'Kimi K2.6',
    inputModalities: ['text', 'image'],
    reasoningEfforts: [],
    contextWindow: 256000,
    maxTokens: null,
  },
  {
    id: 'moonshotai/Kimi-K2.5',
    name: 'Kimi K2.5',
    inputModalities: ['text', 'image'],
    reasoningEfforts: [],
    contextWindow: 256000,
    maxTokens: null,
  },
  {
    id: 'z-ai/glm-5.3-flash',
    name: 'GLM-5.3 Flash',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'high', 'max'],
    contextWindow: 1048576,
    maxTokens: 131072,
  },
  {
    id: 'zai-org/GLM-5.3',
    name: 'GLM-5.3',
    inputModalities: ['text'],
    reasoningEfforts: ['low', 'high', 'max'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'zai-org/GLM-5.2',
    name: 'GLM-5.2',
    inputModalities: ['text'],
    reasoningEfforts: ['high', 'max'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'zai-org/GLM-5.2-Fast',
    name: 'GLM-5.2 Fast',
    inputModalities: ['text'],
    reasoningEfforts: [],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'zai-org/GLM-5.1',
    name: 'GLM-5.1',
    inputModalities: ['text'],
    reasoningEfforts: [],
    contextWindow: null,
    maxTokens: null,
  },
  {
    id: 'zai-org/GLM-5',
    name: 'GLM-5',
    inputModalities: ['text'],
    reasoningEfforts: [],
    contextWindow: 200000,
    maxTokens: null,
  },
  {
    id: 'MiniMaxAI/MiniMax-M3',
    name: 'MiniMax M3',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'MiniMaxAI/MiniMax-M2.7',
    name: 'MiniMax M2.7',
    inputModalities: ['text'],
    reasoningEfforts: [],
    contextWindow: null,
    maxTokens: null,
  },
  {
    id: 'minimax/minimax-m3-free',
    name: 'MiniMax M3 (Free)',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'minimax/minimax-m2.7-free',
    name: 'MiniMax M2.7 (Free)',
    inputModalities: ['text'],
    reasoningEfforts: [],
    contextWindow: 197000,
    maxTokens: null,
  },
  {
    id: 'MiniMaxAI/MiniMax-M2.5',
    name: 'MiniMax M2.5',
    inputModalities: ['text'],
    reasoningEfforts: [],
    contextWindow: 200000,
    maxTokens: null,
  },
  {
    id: 'xiaomi/mimo-v2.5-pro',
    name: 'MiMo V2.5 Pro',
    inputModalities: ['text'],
    reasoningEfforts: [],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'xiaomi/mimo-v2.5',
    name: 'MiMo V2.5',
    inputModalities: ['text', 'image'],
    reasoningEfforts: [],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'Qwen/Qwen3.8-Max-0902',
    name: 'Qwen 3.8 Max 0902',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'xhigh'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'Qwen/Qwen3.8-Max',
    name: 'Qwen 3.8 Max',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'xhigh'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'Qwen/Qwen3.8-27B',
    name: 'Qwen 3.8 27B',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'xhigh'],
    contextWindow: 262144,
    maxTokens: 32768,
  },
  {
    id: 'Qwen/Qwen3.8-Flash',
    name: 'Qwen 3.8 Flash',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'xhigh'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'Qwen/Qwen3.7-Max',
    name: 'Qwen 3.7 Max',
    inputModalities: ['text'],
    reasoningEfforts: [],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'Qwen/Qwen3.7-Plus',
    name: 'Qwen 3.7 Plus',
    inputModalities: ['text', 'image'],
    reasoningEfforts: [],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'Qwen/Qwen3.7-Flash',
    name: 'Qwen 3.7 Flash',
    inputModalities: ['text', 'image'],
    reasoningEfforts: [],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'Qwen/Qwen3.6-Max-Preview',
    name: 'Qwen 3.6 Max Preview',
    inputModalities: ['text'],
    reasoningEfforts: [],
    contextWindow: null,
    maxTokens: null,
  },
  {
    id: 'Qwen/Qwen3.6-Plus',
    name: 'Qwen 3.6 Plus',
    inputModalities: ['text', 'image'],
    reasoningEfforts: [],
    contextWindow: null,
    maxTokens: null,
  },
  {
    id: 'meituan/LongCat-2.0:free',
    name: 'LongCat 2.0',
    inputModalities: ['text'],
    reasoningEfforts: [],
    contextWindow: 1048576,
    maxTokens: null,
  },
  {
    id: 'stepfun/Step-3.7-Flash',
    name: 'Step 3.7 Flash',
    inputModalities: ['text', 'image'],
    reasoningEfforts: [],
    contextWindow: 256000,
    maxTokens: null,
  },
  {
    id: 'stepfun/Step-3.5-Flash',
    name: 'Step 3.5 Flash',
    inputModalities: ['text'],
    reasoningEfforts: [],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'tencent/Hy3',
    name: 'Tencent Hy3 (Free)',
    inputModalities: ['text'],
    reasoningEfforts: [],
    contextWindow: 262144,
    maxTokens: null,
  },
  {
    id: 'tencent/hy3-paid',
    name: 'Tencent Hy3',
    inputModalities: ['text'],
    reasoningEfforts: [],
    contextWindow: 262144,
    maxTokens: null,
  },
  {
    id: 'tencent/hy4-preview',
    name: 'Tencent Hy4 Preview',
    inputModalities: ['text'],
    reasoningEfforts: ['low', 'medium', 'high'],
    contextWindow: 1048576,
    maxTokens: null,
  },
  {
    id: 'google/gemini-3.8-flash',
    name: 'Gemini 3.8 Flash',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'google/gemini-3.7-flash',
    name: 'Gemini 3.7 Flash',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high'],
    contextWindow: 1048576,
    maxTokens: null,
  },
  {
    id: 'google/gemini-3.6-flash',
    name: 'Gemini 3.6 Flash',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'google/gemini-3.5-flash',
    name: 'Gemini 3.5 Flash',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'google/gemini-3.5-flash-lite',
    name: 'Gemini 3.5 Flash Lite',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'google/gemini-3.1-flash-lite',
    name: 'Gemini 3.1 Flash Lite',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'sakana/fugu-ultra',
    name: 'Fugu Ultra',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['high', 'xhigh'],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'nvidia/nemotron-3-ultra-550b-a55b',
    name: 'Nemotron 3 Ultra',
    inputModalities: ['text'],
    reasoningEfforts: [],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'thinkingmachines/inkling',
    name: 'Inkling',
    inputModalities: ['text', 'image'],
    reasoningEfforts: [],
    contextWindow: 256000,
    maxTokens: null,
  },
  {
    id: 'thinkingmachines/inkling-small',
    name: 'Inkling Small',
    inputModalities: ['text', 'image'],
    reasoningEfforts: [],
    contextWindow: 1000000,
    maxTokens: null,
  },
  {
    id: 'poolside/laguna-s-2.1-free',
    name: 'Laguna S 2.1',
    inputModalities: ['text'],
    reasoningEfforts: [],
    contextWindow: 256000,
    maxTokens: 32768,
  },
  {
    id: 'inclusionai/ling-3.0-flash-free',
    name: 'Ling 3.0 Flash',
    inputModalities: ['text'],
    reasoningEfforts: [],
    contextWindow: 256000,
    maxTokens: 32768,
  },
  {
    id: 'inclusionai/ling-3.0-flash-sante:free',
    name: 'Ling 3.0 Flash Sante',
    inputModalities: ['text'],
    reasoningEfforts: [],
    contextWindow: 262144,
    maxTokens: 32768,
  },
  {
    id: 'meta/muse-spark-1.1',
    name: 'Muse Spark 1.1',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh'],
    contextWindow: 1048576,
    maxTokens: null,
  },
  {
    id: 'meta/muse-spark-1.2',
    name: 'Muse Spark 1.2',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh'],
    contextWindow: 1048576,
    maxTokens: null,
  },
  {
    id: 'meta/muse-spark-1.2-contributor',
    name: 'Muse Spark 1.2 Contributor',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh'],
    contextWindow: 1048576,
    maxTokens: null,
  },
  {
    id: 'meta/muse-spark-1.3',
    name: 'Muse Spark 1.3',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    contextWindow: 1048576,
    maxTokens: null,
  },
  {
    id: 'meta/muse-spark-1.3-contributor',
    name: 'Muse Spark 1.3 Contributor',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh'],
    contextWindow: 1048576,
    maxTokens: null,
  },
  {
    id: 'xai/grok-4.5',
    name: 'Grok 4.5',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high'],
    contextWindow: 500000,
    maxTokens: null,
  },
  {
    id: 'xai/grok-4.6',
    name: 'Grok 4.6',
    inputModalities: ['text', 'image'],
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh'],
    contextWindow: 500000,
    maxTokens: null,
  },
]

/** Registry entry for one model id, or undefined when it describes no such model. */
export function commandCodeModelDef(modelId: string): CommandCodeModelDef | undefined {
  return COMMAND_CODE_MODELS.find((model) => model.id === modelId)
}
